### ISSUE TITLE
Problem with KMTEST_MAKE_ID

### ISSUE THREAD

**Issue by cristeigabriel** [SergiusTheBest/kmtest#9] opened 2023-08-26 17:15 UTC
Macros like `SCENARIO` use a macro `KMTEST_MAKE_ID` which relies on `__LINE__`.

If you are to, say, separate tests in `.inl` files, for example:

a.inl:
```
SCENARIO("a") {
// ...
}
```

b.inl:
```
SCENARIO("b") {
// ...
}
```

then include them in your main file like:
```
#include "a.inl"
#include "b.inl"
```

this won't work because the scenarios are both on the same line.

**Comment by SergiusTheBest** [comment] 2023-08-26 17:27
It seems it can be fixed by using the `__COUNTER__` macro. By the way, why do you put them into `.inl` files?

**Comment by cristeigabriel** [comment] 2023-08-26 17:30
> It seems it can be fixed by using the `__COUNTER__` macro. By the way, why do you put them into `.inl` files?

I like to have all of my test scenarios separated, in the end it looks like this

```
#ifdef GAC_TESTING
//
// Tests to be included. In "Header Files" filter, in "tests".
// Whenever you implement a new test section, make a "tests"
// ".inl" file for it, and include it here.
//
#include "alloc.inl"
#include "vector.inl"
#endif
```

**Comment by SergiusTheBest** [comment] 2023-08-31 15:51
The issue is fixed! Please, test it on your side.

**Closed by SergiusTheBest** 2023-08-31 15:51 UTC
Labels: enhancement

**Comment by SergiusTheBest** [comment] 2023-08-31 19:07
Awesome!
